version: "3"

services:
  nautilus_ps:
    container_name: "nautilus_ps"
    image: 5ff6f5507bfb
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - /home/yasmin/catkin_ws:/root/catkin_ws
    network_mode: host
    stdin_open: true
    tty: true
        